In [ ]:
# TENSORFLOW

# thrid day of code

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
 # scalar = single value
scalar=tf.constant(7)   # isme tf lagakar hi hoga kuch bhi pass
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# vector = double value
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

# contant is treated as fix
# variable is treated as changeable

In [ ]:
# next day


a=tf.constant(2)
b=tf.constant(3)
c=tf.constant(4)

In [ ]:
add=tf.add(a,b)
sub=tf.subtract(a,b)

In [ ]:
print(add)
print(sub)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)


In [ ]:
mul=tf.multiply(a,b)


In [ ]:
print(mul)

tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
# or otherwise

In [ ]:
print('add',add.numpy())

add 5


In [ ]:
print('sub=',sub.numpy())

sub= -1


In [ ]:
print('mul=',mul.numpy())

mul= 6


In [ ]:
matrix1=tf.constant([[1,2],[3,4]])


matrix2=tf.constant([[5,6],[7,8]])

In [ ]:
product=tf.matmul(matrix1,matrix2)

In [ ]:
product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

# tensor variable

In [ ]:
tf1=tf.Variable(42)
print(tf1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>


In [ ]:
tf1.assign(50)    # assign se variable ki value change ho jati hai
tf1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=50>

In [ ]:
f64=tf.Variable(89,dtype=tf.float64)

In [ ]:
f64

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=89.0>

In [ ]:
# the rank dimensions

In [ ]:
tf2=tf.Variable([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
tf2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)>

In [ ]:
# shape = ( repeated, how many rows , how many columns )

In [ ]:
tf.rank(tf2)   # dimesnions

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
scalar=tf.constant(7)

In [ ]:
scalar  # rank is 0 because it is single in number

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vactor=tf.constant([10,10])
vactor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix=tf.constant([[10,7],[9,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 9, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[19,11,12]],[[13,14,15],[16,17,18]]])

In [ ]:
tensor  # ( repeated, rows,columns)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [19, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
changeable_tensor =tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
 # requires assign method
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# we cant change the constant becasue it is unchangeable in nature

In [ ]:
# creating two values but the same tensor

In [ ]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))


random_1,random_2,

random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
random_1=tf.random.Generator.from_seed(36)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))


random_1,random_2,    random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.645002  ,  0.18022095],
        [-0.14656258,  0.34374258],
        [ 0.41367555,  0.17573498]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
# shuffle hokr aayegi ab value

In [ ]:
not_shuffles=tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffles)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
# if we use seed then we will get the same parameter

In [ ]:
tf.random.shuffle(not_shuffles,seed=42)  # ye uper wala dikha rha hai
                                          # but ye same ya fix nhi rhega



# next day 99


NameError: name 'not_shuffles' is not defined

In [ ]:
import tensorflow as tf

In [ ]:
tf.random.set_seed(42)

In [ ]:
tf.random

<module 'tensorflow._api.v2.random' from '/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/random/__init__.py'>

In [ ]:
import numpy as np

In [ ]:
numpy_a=np.arange(1,25,dtype=np.int32)
a=tf.constant(numpy_a,shape=(2,3,4))
numpy_a,a


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [ ]:
rank_4=tf.zeros([2,3,4,5])
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
print("Datatype of element:",rank_4.dtype)
print("Number of dimensoins (rank):",rank_4.ndim)
print("Shape of tensor:",rank_4.shape)
print("Elements along axis 0 of tensor:",rank_4.shape[0])
print("Elements along last axis of tensor",rank_4.shape[-1])
print("Total number of elements (2*3*4*5):",tf.size(rank_4).numpy ())

Datatype of element: <dtype: 'float32'>
Number of dimensoins (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor 5
Total number of elements (2*3*4*5): 120


In [ ]:
# get the first 2 items of each dimensoin
rank_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# create  a rank 2 tensor (2 dimensions)
rank_2=tf.constant([[19,7],
                    [3,4]])
rank_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# add an extta dimension (to the end)
rank_3 =rank_2[..., tf.newaxis]
rank_2,rank_3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[19,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[19],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [ ]:
# you can add values to a tensor using the addition opertor
tensor = tf.constant ([[10,3],[33,7]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 13],
       [43, 17]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [33,  7]], dtype=int32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [330,  70]], dtype=int32)>

In [ ]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -7],
       [23, -3]], dtype=int32)>

In [ ]:
# use the tensorflow function equivaluent of the '*' n(multiply) operator
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [330,  70]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [33,  7]], dtype=int32)>

In [ ]:
print("tensor")
tf.matmul(tensor,tensor)

tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[199,  51],
       [561, 148]], dtype=int32)>

In [ ]:
# matrix multipication with python operator'@'
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[199,  51],
       [561, 148]], dtype=int32)>

In [ ]:
X = tf.constant ([[1,2],
                  [3,4],
                  [3,5]])

In [ ]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [3, 5]], dtype=int32)>

In [ ]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 3],
       [2, 4, 5]], dtype=int32)>

In [ ]:
B = tf.constant([1.7,7.4])
C = tf.constant([8.3,5.4])
B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.3, 5.4], dtype=float32)>)

In [ ]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
C=tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.3, 5.4], dtype=float32)>

In [ ]:
# create tensor with negative values
D = tf.constant([-3,-5])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3, -5], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [ ]:
# create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0,high=100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([63, 46, 58, 78, 97, 90, 85, 70, 15, 53, 40, 67, 61, 62, 19, 70, 25,
       29, 69, 64, 94, 84, 77, 37, 12, 24, 15, 69, 13,  1, 58, 98, 24, 42,
       20, 79, 30, 85, 15, 76, 97, 14, 55, 57, 97, 72, 17, 43, 79, 32])>

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=53>